Repository tannerdolby/what-to-watch, pull requests merged in 2020-10, with the labels that each got.

#1 Added Archer to the list of What To Watch.
  src/shows/archer.md
Labels: enhancement, hacktoberfest-accepted

#3 Update bloodline.md
  src/shows/bloodline.md
Labels: bug

#2 Create raised-by-wolves.md
  src/shows/raised-by-wolves.md
Labels: hacktoberfest-accepted

#4 Added community tv series
  src/shows/community.md
Labels: hacktoberfest-accepted
